//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Remotephone.Properties {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Remotephone.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Byte[].
        /// </summary>
        internal static byte[] Remotephone {
            get {
                object obj = ResourceManager.GetObject("Remotephone", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Remotephone1 {
            get {
                object obj = ResourceManager.GetObject("Remotephone1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Icon podobny do zasobu (Ikona).
        /// </summary>
        internal static System.Drawing.Icon Remotephone2 {
            get {
                object obj = ResourceManager.GetObject("Remotephone2", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Byte[].
        /// </summary>
        internal static byte[] scrcpy {
            get {
                object obj = ResourceManager.GetObject("scrcpy", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Retail Branding,Marketing Name,Device,Model
        ///,,AD681H,Smartfren Andromax AD681H
        ///,,FJL21,FJL21
        ///,,hws7721g,MediaPad 7 Youth 2
        ///1&amp;1,1&amp;1 Puck,diw362_1u1,DIW362P 1U1
        ///1&amp;1,1&amp;1 TV Box,diw387_1u1,DIW387 1U1
        ///1&amp;1,DIW387-1&amp;1,diw387_1u1,DIW387 1U1
        ///10.or,10or_G2,G2,10or G2
        ///10.or,D,10or_D,D
        ///10.or,E,E,E
        ///10.or,G,G,G
        ///10.or,G2,G2,G2
        ///3222222 Satelital,G706,G706,G706
        ///3BBTV,TBBTV01,TBBTV01,TBBTV01
        ///3Go,GT10K3IPS,GT10K3IPS,GT10K3IPS
        ///3Go,GT70053G,GT70053G,GT70053G
        ///3Go,GT7007EQC,GT7007EQC,GT7007EQC
        ///3Q,OC1020A,OC1020A, [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string supported_devices {
            get {
                return ResourceManager.GetString("supported_devices", resourceCulture);
            }
        }
    }
}
